# Generated by Django 3.1.1 on 2020-10-28 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_create_initial_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='can_see_explanation',
            field=models.BooleanField(default=False, verbose_name='Can the students see the explanation?'),
        ),
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=models.CharField(blank=True, default='', max_length=2048, verbose_name='Explanation'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='can_redo',
            field=models.BooleanField(default=False, verbose_name='Can the students redo the quiz?'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='can_see_correction',
            field=models.BooleanField(default=True, verbose_name='Can the students see the correction?'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='use_katex',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=2048, verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
