# Generated by Django 3.1.1 on 2020-09-28 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0004_insert_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='can_see_explanation',
            field=models.BooleanField(default=False, verbose_name='Can see the explanation?'),
        ),
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=models.CharField(blank=True, default='', help_text='You can use the markdown language.', max_length=2048, verbose_name='Explanation'),
        ),
    ]
