# Generated by Django 3.1.1 on 2020-09-28 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0005_auto_20200928_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='can_see_correction',
            field=models.BooleanField(default=True, verbose_name='Can the student see the correction?'),
        ),
        migrations.AlterField(
            model_name='question',
            name='can_see_explanation',
            field=models.BooleanField(default=False, verbose_name='Can the student see the explanation?'),
        ),
    ]
